[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
dqt = { workspace = true }
dqt-executor-spark35 = { workspace = true }
dqt-artifact-iceberg = { workspace = true }

[dependency-groups]
dev = [
    "black>=26.5.1",
]

[project]
name="dqt-root"
version="0.0.1"
dependencies=[
    "great-expectations>=1.20.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
]