# Source - https://stackoverflow.com/a/50156706
# Posted by hoefling, modified by community. See post 'Timeline' for change history
# Retrieved 2026-06-26, License - CC BY-SA 4.0

[pytest]
pythonpath = .
